### ISSUE TITLE
[TASK] Set up backend API for logging user’s swipes (like/dislike) for listings

### ISSUE THREAD

**Issue by raccoonrick** [harismah/Dwella#116]
**Description** : Create the backend logic for swiping on a listings on the listings details page and verify that the user only views unique listings.

**Actions**:
- Swipe left: Dislike the listing, add it to the Views table and go to the next listing
- Swipe right: Bookmark the listing, add it to the Views and Bookmarks table and go to the next listing
- Refresh: View the listings again to reswipe, remove the listings from the Views table to allow the user to see them again

Related to: [#30 , #41, #24]
PR resolving this issue: #121

**Comment by CarlaShawi** [comment]
This task is closed by pr [#121]
