### ISSUE TITLE
[Documentation] Risk Assessment

### ISSUE THREAD

**Issue by Tharsipa** [harismah/Dwella#12]
**Description:** This issue is created to identify and eliminate domain-specific risks that could severely impact or even "kill" the success of our project. The objective is to assess risks without writing any production code, focusing on issues that are unique to our project's context. The risks we aim to address are directly related to our project's goals and scope. 

Link to information (Wiki): https://github.com/CodePioneerX/Dwella/wiki/Risks

**Comment by louisa-lina** [comment]
I verified, everything looks good to me. I will close the issue.
