### ISSUE TITLE
[Documentation] Deciding Tech Stack

### ISSUE THREAD

**Issue by CarsonSSk** [harismah/Dwella#13]
**Description:** This issue is created to finalize the tech stack for our project. After discussing various options, we’ve decided that a more unified tech stack would benefit our development process. Below is a summary of the conversation we had for deciding the tech stack.

**Discussion Summary**
Initially, we considered using React for the frontend and Django for the backend.
However, after further evaluation, we believe that React for the frontend and Node.js + Express.js for the backend would be a better option due to the following reasons:

- Unified Language (JavaScript): Both the frontend (React) and backend (Node.js + Express.js) would use JavaScript, allowing us to maintain a single language across the entire stack. This makes sharing, testing, and maintaining code logic easier.
- Flexibility & Scalability: Node.js provides greater flexibility and scalability in development. It’s well-suited for handling real-time features, such as in-app messaging, which would be beneficial for potential chat or real-time updates.
- Express.js for Backend: Express.js, a lightweight framework, simplifies building efficient APIs, making it easier to handle high user interactions and promote scalability.
- PostgreSQL for the Database: We are leaning towards PostgreSQL for the database due to its robust feature set and scalability.
- Mobile Transition: This tech stack would make transitioning from a web app to a mobile app easier, which may be an option in the future.

After taking into consideration the use of stable versions of each tool, the following tech stack was decided:

Frontend: React (v18)
Backend: Node.js (v20) + Express.js (v4.18.3)
State Management: Redux (v4.2.1)
Database: PostgreSQL (v16)

Discussion ref: https://github.com/CodePioneerX/Dwella/discussions/6
Wiki ref: https://github.com/CodePioneerX/Dwella/wiki/Infrastructure-and-tools

**Comment by harismah** [comment]
As mentioned by @CarsonSSk, after discussing this with the team, We finalized the tech stack and chose a Javascript-based framework, specifically for reducing learning requirements, as well as it is considered relevant to today's development. Finally, it provided benefits for chat-enabled features, by being efficient and fast when it comes to data processing.

**Comment by louisa-lina** [comment]
The use of Node.js (v20) + Express.js (v4.18.3) is a perfect choice in complement with React (v18) in the front end as both are Javascript based language.
