### ISSUE TITLE
[Documentation] Deciding Testing Frameworks and Libraries

### ISSUE THREAD

**Issue by CarsonSSk** [harismah/Dwella#14]
**Description:** This issue is created to finalize the testing frameworks we will use for our project. We want to ensure that we have a consistent and reliable testing setup that covers the frontend, backend, state management, and end-to-end functionality of our web application. Below is a summary of the frameworks we considered and the reasoning behind our final decision.

1. Jest (Frontend):
Purpose: Primarily considered for unit and integration testing of React components.
Why Considered: Jest is already bundled with React projects and is one of the most popular and reliable testing frameworks for JavaScript applications. It supports features like mock functions, built-in assertions, and snapshot testing for UI components.
2. React Testing Library:
Purpose: Tested as a complementary tool for Jest, focused on testing React components from the user’s perspective.
Why Considered: Encourages best practices by focusing on real user interactions with the UI rather than testing implementation details.
3. Mocha + Chai (Backend):
Purpose: Commonly used for testing Node.js applications, Mocha is a test runner, and Chai is an assertion library.
Why Considered: Provides flexibility in writing both unit and integration tests for the backend, especially for API routes and database interactions.
4. Supertest (Backend):
Purpose: Specifically used for testing HTTP endpoints in Express.js applications.
Why Considered: Integrates well with backend testing to simulate and assert HTTP requests and responses.
5. Cypress (End-to-End):
Purpose: Used for end-to-end testing by simulating user interactions across the frontend and backend.
Why Considered: Cypress provides an all-in-one testing solution for frontend and backend integration testing. It’s particularly well-suited for end-to-end scenarios and testing the complete user flow.

After evaluating the tools, we decided to streamline our testing process by focusing on fewer frameworks that can cover both the frontend and backend efficiently. The following is our chosen testing stack:

**Frontend Testing: Jest**

We will use Jest for both unit and integration testing of React components. It’s a natural fit since Jest is already integrated into most React setups and offers powerful tools like mocks and spies. Using Jest also ensures we can test state management, including Redux, effectively.
React Testing Library will be used alongside Jest for testing user interactions with components from the user’s perspective.

**Backend Testing: Jest + Supertest**

We decided to use Jest for backend testing as well, primarily because it offers consistency across the project. Jest can handle both unit tests (for controllers, services, etc.) and integration tests, while Supertest will be used specifically to test our Express.js API routes.
This unified approach simplifies the development and testing process, ensuring that the same tool (Jest) handles both frontend and backend.

**End-to-End Testing: Cypress**

For full end-to-end testing, we will use Cypress to simulate real user flows across both the frontend and backend. Cypress is feature-rich for E2E testing, offering powerful tools for debugging and simulating complex user interactions with real-time feedback.
Cypress is ideal for ensuring that the user experience is seamless from start to finish, integrating the frontend and backend tests.

**Testing State Management: Jest**

We will use Jest to test Redux actions, reducers, and their integration with React components. Since Redux is a key part of our app's state management, we need to ensure that state transitions happen as expected and that components respond to state changes appropriately.

**Comment by harismah** [comment]
Thanks for providing such a detailed summary of the testing frameworks and the rationale behind the choices. After working with you on evaluating the options, I fully support the final selection. This setup not only ensures consistency across the project but also simplifies our testing process by focusing on efficient and reliable tools.
