### ISSUE TITLE
[BUG] Database Update on Double Tap Not Reflected to User Interface

### ISSUE THREAD

**Issue by NicholasWahome** [harismah/Dwella#146]
**Description:** When a user double taps the hearting/bookmarking icon, the database is updated successfully, but the updated response is not reflected in the user interface. This results in users not receiving feedback on their action, potentially causing confusion about whether their action was successful.

Steps to Reproduce:

Navigate to a listing that can be hearted/bookmarked.
Double tap the hearting/bookmarking icon.
Observe that the database updates, but the user interface does not reflect this change.
Expected Result: The user interface should update to show the new state (e.g., hearted/bookmarked) immediately after the double tap.

Actual Result: The database updates successfully, but there is no visual feedback or confirmation for the user.

Frequency of Occurrence: 100% of the time

Severity: Medium

Screenshots/Attachments:

https://github.com/user-attachments/assets/402a32b6-3894-4d53-8be8-78941a3050da

Additional Notes:

This issue affects user experience as users may be unsure if their action was successful.
The backend appears to function correctly, indicating that the issue lies within the front-end response handling.
Suggested Fix:
Implement a mechanism to update the user interface in response to the successful database update after a double tap on the hearting/bookmarking icon.

PR Resolving this issue #168

**Comment by harismah** [comment]
Perfect everything is responding as expected. Will close the issue now!
