### ISSUE TITLE
[Documentation] Overall Architecture and Class Diagrams

### ISSUE THREAD

**Issue by raccoonrick** [harismah/Dwella#15]
**Description:** This issue involves creating and finalizing the architecture and class diagrams for the Dwella project to provide a structured foundation for development. These diagrams will serve as a blueprint for the application’s structure, helping the team understand key components, relationships, and data flows. The diagrams will be used to guide both frontend and backend development, ensuring consistency and clarity in design.

Link to info: https://github.com/CodePioneerX/Dwella/wiki/Overall-Architecture-and-Class-Diagrams

**Comment by raccoonrick** [comment]
Initial class diagram and domain model
![domain model](https://github.com/user-attachments/assets/93624ef6-73e6-4101-9875-45a0cc79e269)
![Class Diagram-Class Diagram drawio](https://github.com/user-attachments/assets/3c61a05d-cf58-402b-a61b-5da9f016f716)

**Comment by harismah** [comment]
I think that it's a good start, I provided some feedback on this rough draft, as to what I think can be merged, removed, or added. Please take a look and let me know if there are any questions.

<img width="862" alt="Screenshot 2024-09-25 at 4 13 08 PM" src="https://github.com/user-attachments/assets/75286773-2b9f-4406-b530-0d7469f3059c">

**Comment by v-vasco** [comment]
Hadn't seen the issue posted earlier, here's the ER diagram for the database I had done. Seeing your feedback for the class diagram, I'll update the ER diagram as well to implement the feedback.

![image_2024-09-25_173257303](https://github.com/user-attachments/assets/e96f2a87-3c94-4add-a957-2534c25d1ff9)

**Comment by raccoonrick** [comment]
Here's the new updated diagram based on the comments
![class diagram](https://github.com/user-attachments/assets/24f9bf37-9f1f-4ccf-974d-5f7bbb5aa97c)

**Comment by Swaggyyyy2** [comment]
Here's the updated class diagram according to the recommendations let us know if anything needs to be changed.

**Comment by v-vasco** [comment]
I've attached the updated ER diagram based on the updates to the class diagram. Let me know if anything needs to be changed further.

![image_2024-09-27_000241318](https://github.com/user-attachments/assets/d45320e1-71f4-4b42-b9e8-054f71cbdade)

**Comment by harismah** [comment]
I believe everything is in accordance, as discussed during the call and after reviewing the diagrams. Good work! Thank you everyone!
