### ISSUE TITLE
[BUG] Profile Page Responsiveness

### ISSUE THREAD

**Issue by harismah** [harismah/Dwella#164]
**Description:**

The current layout is responsive and displays as intended on larger screens, but it encounters issues on mobile devices. When viewed on smaller screens, elements do not adjust properly, resulting in a broken or misaligned layout where content may overflow, text can be cut off, or components do not fit within the viewport. This breakdown in responsiveness affects the overall user experience, making the page difficult to navigate and reducing readability on mobile devices.

PR resolving this issue #183 

![image](https://github.com/user-attachments/assets/e2233995-83e3-4422-a3ea-e62d67a249f9)
![image](https://github.com/user-attachments/assets/81fc5e5e-2909-4d1d-8318-2d2765913f84)
![image](https://github.com/user-attachments/assets/57792a7b-9e99-455b-be53-6829dae7b155)

**Comment by NicholasWahome** [comment]
According to PR: #183 this has been completed
