### ISSUE TITLE
[TASK] Set Up Live Logging for Backend

### ISSUE THREAD

**Issue by CarsonSSk** [harismah/Dwella#18]
**Description:** This issue involves setting up live logging for the backend of the Dwella application to track and manage server activity and requests. The logging system will be implemented using the Winston logging library combined with Morgan for HTTP request logging. This allows us to capture, format, and store logs for incoming requests, server status, and error messages.

PR to resolve this issue: #20

**Comment by harismah** [comment]
The implementation of live logging using Winston and Morgan is a great addition to the backend. Everything seemed to work on my end. The setup ensures that we can efficiently track and monitor server activity, incoming requests, and error messages in real time. The combination of these two logging libraries will provide valuable insights into our system’s health and help with debugging. Everything looks well-structured, and I’m confident this will improve our backend's reliability. I’m closing the issue now. Great job!
