### ISSUE TITLE
[BUG] Page Items Blocking Mobile Navigation Menu

### ISSUE THREAD

**Issue by v-vasco** [harismah/Dwella#188]
Description: While on the explore page in a mobile display, the filter button, search bar, and search button block out part of the navigation menu when it is opened. For better UX, the navigation menu should not be blocked by any other elements on the page when opened.  Similar bug was found on the swipe page. 

PR resolving this bug: #209

This bug on the explore page can be seen in the demo below:

https://github.com/user-attachments/assets/4c70f77a-8f5e-480e-8896-4fd2556fcb3e

For the swipe page:
![image](https://github.com/user-attachments/assets/0e799491-aa16-448a-8a5f-f7c736ef4e06)

**Comment by harismah** [comment]
Issue was resolved by #209
