### ISSUE TITLE
[Documentation]: Sprint Delivery and Retrospective Report

### ISSUE THREAD

**Issue by CarlaShawi** [harismah/Dwella#22]
**Description:**  This issue aims to clarify the team's progress in iteration 1, covering completed tasks, challenges faced, and solutions applied. It aims to improve future efficiency by reflecting on current workflows and outlining priorities and objectives for the next iteration.

Related to PR: #47

**Comment by NicholasWahome** [comment]
As the documentation has been merged. It is a complete issue. 
I will now close it. For reference to the closed pr: #47
