### ISSUE TITLE
[Documentation] Diversity Statement

### ISSUE THREAD

**Issue by harismah** [harismah/Dwella#23]
**Description:** Diversity and Inclusion wiki page for the Dwella project. This page outline how Dwella is committed to fostering diversity and inclusion within the platform and services we provide, specifically in the areas of renting, finding roommates, and searching for living spaces. The page provides a clear and concise overview of our principles and how they apply to our user base.

Link To: https://github.com/CodePioneerX/Dwella/wiki/Diversity-statement

**Comment by CarsonSSk** [comment]
LGTM! Thanks.
