### ISSUE TITLE
[US] Governmental Verification ID

### ISSUE THREAD

**Issue by harismah** [harismah/Dwella#26]
### Description:
As a registered user, I want to submit my government-issued ID for verification so that I can ensure my identity is confirmed and gain access to restricted features.

### Story Points:
5

### Priority:
1 (High Priority)

### Risk:
Medium

### Business Value:
H (High)

### Child of (if applicable) :
- #36

### Acceptance Criteria:
- The feature should allow users to upload valid government-issued ID types (passport, driver’s license, national ID).
- The system must verify the ID through an internal verification process.
- Users must be notified if their ID verification is successful or rejected within 48 hours.
- Users must be able to re-submit their ID if rejected, with reasoning for rejection.
- Verification status (verified/not verified) should be displayed on the user’s profile page.

### Task Breakdown (if applicable):
- #75
- #76
- #152
- #153

### Implementation Breakdown:
- Create a user interface to allow the uploading of government-issued IDs.
- Validate file types and formats (PDF, JPEG, PNG).
- Integrate the verification system (internal).
- Store and process the verification status in the database.
- Create a status page to update users about their verification status.
- Display the verification status on the user’s profile page.

Here’s the **Testing** section with different indented bullet points:

---

### **Testing (if applicable)**:

- **Unit Tests**: 
  - Test the ID upload form and file type validation.
  - Test user status page.
  
- **Integration Tests**: 
  - Test the update of user profiles with verification status.

---

**Comment by NicholasWahome** [comment]
First iteration of this has been completed
