### ISSUE TITLE
[TASK] Review and Verify Sprint 1-3 (and Sprint 4 if Time Permits)

### ISSUE THREAD

**Issue by harismah** [harismah/Dwella#272]
**Task Objective**: 
The purpose of this task is to perform a comprehensive review of all epics, issues, tasks, bugs, tests, pull requests (PRs), and any additional issues created during Sprints 1 through 3, ensuring that each element is formatted correctly, assigned appropriately, and organized in the correct sprint order. If time permits, Sprint 4 will also be reviewed. Work alongside @louisa-lina to help ensure everything was In order

![image](https://github.com/user-attachments/assets/bcdbfbda-0ce0-455b-af6d-f0f6d0178d85)

**Comment by louisa-lina** [comment]
Everything up until sprint 3 has been reviewed & some part of Sprint 4. Thank you !
