### ISSUE TITLE
Epic 4: Personalized Listing

### ISSUE THREAD

**Issue by raccoonrick** [harismah/Dwella#286]
### Description:

As a potential renter, I want to be able to view personalized recommendations for listings based on my previous swipes/selections so that I can make my search for listings more efficient.

### Story Points:

8

### Priority:

2

### Risk:

Low

### Business Value:

H (High)

### Rationale:

Personalized and tailored recommendations save users time and effort by showing them properties that they are more likely to like. It also streamlines the search process for renters by helping them find suitable listings faster.

### Acceptance Criteria:

1. The swipe page should display personalized recommendations for listings based on location, type, amenities, price, from previous swipes.
2. Recommendations should be based on listings that the user has swiped right on.
3. Recommendations should exclude listings that the user has swiped left on (disliked) and listings similar to those.

### User Stories:

- #287 
- #288

### Implementation Breakdown:

- Develop the backend logic for personalized listings.
- Develop the backend API routes for getting recommended listings for a specific user.
- Update the Swipe page by showing the new recommended listings rather than listings not seen by the user.

### Testing (if applicable):

- **Blackbox Testing**: Verify that personalized recommendations appear on the Swipe page and that they are based on previously liked (swiped right) listings.
- **Unit Testing**: Ensure all API routes work as expected and save data correctly
- **Regression Testing**: Verify that the basic swiping functionality works correctly after implementing personalized listings. Ensure that other features, such as listings description and POIs still function as expected.

### Demo Steps:

1. Log in as a renter.
2. Navigate to the "Swipe" page.
3. Swipe right on liked listings and left on disliked listings.
4. Refresh the page to view new personalized listings.
5. View listings and ensure listings are similar to liked (swipe right) listings.

**Comment by CarlaShawi** [comment]
This epic was completed successfully by completing all user stories and tasks by pr #298 and pr #301
