### ISSUE TITLE
[US] Update Swipe to match listings with personalized listing

### ISSUE THREAD

**Issue by CarlaShawi** [harismah/Dwella#288]
### Description:

As a user, I want the Swipe page to display personalized recommendations so that I can see listings that align with my interests.

### Story Points:

3

### Priority:

2

### Risk:

Low

### Business Value:

H (High)

### Child of (if applicable) :

Epic 4: Personalized Listing [#286 ]

### Acceptance Criteria:

- The Swipe page should now only show listings recommended by the backend based on previous swipes.
- Ensure that listings disliked by the user are not displayed in future recommendations.

### Task Breakdown (if applicable):

- #291 
- #292 

### Implementation Breakdown:

- Modify Swipe page to display recommended listings.
- Integrate with the backend to fetch new listings after each swipe.

### Testing (if applicable):

- **Unit Tests**: Test that the Swipe page components render correctly and the API integration function retrieves and filters recommendations as expected.
- **Integration Tests**: Verify that the Swipe page displays correct recommendations through API calls, updating in real-time with user swipes.

**Comment by raccoonrick** [comment]
All tasks completed with PR #301
