### ISSUE TITLE
[Documentation] Concordia IP and Liability Opt-Out Form

### ISSUE THREAD

**Issue by harismah** [harismah/Dwella#3]
The Opt-out form is required to be submitted by all members stating that Concordia University does not claim ownership of any intellectual property (IP) generated through coursework and is not liable for any work completed for the course. 

IP Opt-out form: https://drive.google.com/file/d/1loMvdufWmoD1eue6AdDgFyufI_ycEuWJ/view?usp=sharing

**Comment by harismah** [comment]
I was told by Professor Rigby, that we might not be required to have a Concordia opt-out form any longer during the office hours on Zoom — 09/11/2024.

**Comment by louisa-lina** [comment]
Ok, thank you for mentioning it. I will close the issue.
