### ISSUE TITLE
[Documentation] Persona

### ISSUE THREAD

**Issue by louisa-lina** [harismah/Dwella#31]
**Description:**

The task involves creating two detailed user personas to represent typical users of the Dwella platform. These personas will help the development team better understand the needs of both tenants and landlords and ensure that the platform’s features address their specific challenges and goals.

link to Wiki: https://github.com/CodePioneerX/Dwella/wiki/Persona

**Comment by CarlaShawi** [comment]
![image](https://github.com/user-attachments/assets/221f4adb-a06a-4ad2-8d3e-30fc3410b6d3)
when clicking at link, I'm not able to see the personas, not sure If it's only on my side

**Comment by CarsonSSk** [comment]
Hey @CarlaShawi, I just tested on my end and it seems to work. Might have been a bug with github. This is what I see: 
![image](https://github.com/user-attachments/assets/0a7eb46a-bae9-405d-9e61-f384d4a141c6)
