### ISSUE TITLE
[US] Categorized Points of Interest on Explore Page

### ISSUE THREAD

**Issue by Tharsipa** [harismah/Dwella#310]
### Description:

As a user, I want to see categorized points of interest (e.g., restaurants, entertainment, transit) around available listings so that I can easily explore and evaluate the amenities near a property.

### Story Points:

3

### Priority:

2

### Risk:

Medium

### Business Value:

H (High)

### Child of:

- #282

### Acceptance Criteria:

- Users can view points of interest near listings categorized into predefined categories (e.g., restaurants, entertainment, transit).
- The categories should be clearly labeled and distinct.
- Clicking on a category displays relevant points of interest on the map.
- Users can toggle visibility of different categories on the map.
- The points of interest should update dynamically based on the selected listing.

### Task Breakdown:

- #311 
- #318 

### Implementation Breakdown:

1. **API Integration**: Connect to external or internal APIs to fetch points of interest data by category.
2. **Category Component**: Develop a UI component for category selection.

### Testing:

- **Unit Tests**:
  - Test category selection logic.
  - Test API data parsing for points of interest.
- **Integration Tests**:
  - Verify API integration correctly retrieves and displays categorized data.
  - Ensure map displays accurate points of interest for selected categories.

**Comment by NicholasWahome** [comment]
This issue was completed with PR:  https://github.com/CodePioneerX/Dwella/pull/319
