### ISSUE TITLE
Epic 9: User Viewing

### ISSUE THREAD

**Issue by harismah** [harismah/Dwella#323]
### Description:

As a user, I want to view the platform with varying functionality depending on my login status and role (Lessor, Lessee, or Signed out) so that I can access relevant features like creating listings or bookmarking other listings.

### Story Points:

7

### Priority:

2

### Risk:

Small

### Business Value:

M (Medium)

### Rationale (optional):

This epic ensures that the platform provides tailored user experiences based on the user's role or login status. This differentiation improves usability and engagement by presenting the most relevant functionality to each type of user. 

### Acceptance Criteria:

- Users signed in as registered Lessors can access functionality like creating listings, viewing all their listings, and editing their listings.
- Users signed in as Lessees can view listings and bookmark others' listings.
- Signed-out users can only browse public content with limited functionality.
- Unregistered Lessors (Lessors who haven’t registered as a host) will see a "Register" option on the Hosting page instead of options to manage listings.
- Bookmarked listings can be viewed in a separate section, excluding the host's own listings.

### Task Breakdown:

- #293 

### Implementation Breakdown:

1. Add logic to detect user login status and role (registered Lessor, unregistered Lessor, Lessee, Signed out).
2. Develop frontend components for displaying user-specific views.
3. Integrate backend API to fetch and display relevant functionality and data.
4. Add a bookmarks feature to display other listings for Lessee users.
5. Ensure proper conditional rendering based on user type and login state.

### Testing (if applicable):

- **Blackbox Testing**:
  - Verify that registered Lessors can access the "Create Listing," "View Listings," and "Edit Listings" functionality.
  - Ensure unregistered Lessors see a "Register" option on the Hosting page and cannot access listing management functionality.
  - Ensure Lessees can view and bookmark other listings.
  - Confirm signed-out users can only browse public content.
  - Test visibility and functionality of bookmarks for Lessees.
- **Regression Testing**:
  - Test for unintended changes in other parts of the platform after implementation.

### Demo Steps:

1. **For Registered Lessor**:
   - Sign in as a registered Lessor.
   - Navigate to the header and select the "Hosting" option.
   - Access relevant options to manage listings, including "Create Listing" and "View All Listings."
   - Create a new listing and verify its successful addition to the listings page.
   - View all created listings and verify details such as title, price, and availability.
   - Edit an existing listing and confirm the changes are saved and reflected in the listings page.

2. **For Lessee**:
   - Sign in as a Lessee.
   - View listings and add a bookmark to a listing.
   - Navigate to bookmarks and verify that only other listings are displayed.
   - Navigate to the header and select the "Hosting" option.
   - Verify that a "Register" option is displayed instead of listing management options.
   - Attempt to access the "Create Listing" or "Manage Listings" page and confirm access is denied.

3. **For Signed-out User**:
   - Sign out of the platform.
   - Attempt to access restricted functionality and confirm it is unavailable.
   - Browse publicly available listings.

**Comment by NicholasWahome** [comment]
This issue is completed
