### ISSUE TITLE
[TASK] Restricting Appropriate Viewing Access and Functionality Based on User Type

### ISSUE THREAD

**Issue by harismah** [harismah/Dwella#324]
Description:

This task focuses on implementing role-based access control to ensure that functionality and UI options are displayed appropriately based on the user's role (Lessor, Lessee). Thus, a user shouldn't be able to see or access functionality they don't have access to by entering the appropriate link. 

Task related to 
- #293 

PR Resolving this issue:
- #296 
- #349

**Comment by NicholasWahome** [comment]
This issue is resolved check above description for links.
