### ISSUE TITLE
[TASK] Bookmarking Listings for Lessees and Lessors Appropriate to Other Users

### ISSUE THREAD

**Issue by harismah** [harismah/Dwella#325]
**Description:**
This task focuses on enabling both Lessees and Lessors to view and manage their bookmarked (favourite) listings. The key requirement is that a host cannot bookmark or see their own listings in their favourites, as well as shouldn't see an option for liking their listing, instead should see an edit icon. 

Task Related to:
- #293 

PR Resolving this issue:
#328

**Comment by v-vasco** [comment]
I've addressed this in the two most recent commits on the SpecificListing page in the branch linked to this task.  If the host user views their own listing, the heart button is replaced with an edit button. The heart button still displays if they look at other user's listings.

Still needs to be applied on the ExplorePage and potentially the Swipe Page. Maybe could be applied directly in the API to block any attempts of the host user to bookmark their own listing.
