### ISSUE TITLE
[TASK] UI/UX Design for Dwella Platform

### ISSUE THREAD

**Issue by louisa-lina** [harismah/Dwella#33]
**Description:** The task is to design the user interface (UI) and user experience (UX) for the Dwella platform using Figma. The designs will focus on creating a seamless and intuitive experience for both tenants and landlords. The following pages are expected to be included in the UI/UX design:

- Home Page
- Login Page
- Sign Up Page
- Profile Page
- Profile Editing Page
- Swiping Page
- Listing Page
- Account Verification Page
- Account Verification Status Page

These designs should reflect Dwella’s core features, ensuring ease of navigation and visual consistency across all pages.

**Expected Output:**
- A complete set of Figma UI/UX designs for all listed pages.
- User-friendly navigation and clear layout.
- Visual elements that align with the Dwella brand identity.
- Functional designs that enhance the overall user experience for tenants and landlords.

**Provided Link:** https://www.figma.com/design/MMDJUU34C5u9ZpvLYMlIsF/Dwella-Concept?node-id=45-3605&t=bVbdiE1fEpkkW5hs-1

**Comment by harismah** [comment]
Everything looks good, thanks for the work team!

**Comment by louisa-lina** [comment]
Nicee it was a pleasure working with you guys for this issue.
