### ISSUE TITLE
[US] Account Registration as Lessee & Lessor

### ISSUE THREAD

**Issue by Tharsipa** [harismah/Dwella#34]
### Description:
As a user, I want to register an account either as a host (lessor) or tenant (lessee) so that I can access the platform, manage properties, search for apartments, and connect with potential roommates.

### Story Points:
5

### Priority:
1

### Risk:
Medium

### Business Value:
H (High)

### Child of (if applicable):
Epic 8: User Verification and Authentication #36

### Acceptance Criteria:
- Users must be able to register with an email, password, and user type selection (Host or Tenant).
- The registration form must validate required fields (e.g., email, password, name).
- User type (Host or Tenant) is mandatory and determines the user interface experience.
- In case of an error (e.g., invalid email or password), users should see a relevant error message.
- Email confirmation is triggered upon successful registration.
- User data is stored in the database upon registration.

### Task Breakdown:
- [TASK] Create a registration form that captures basic info (name, email, password, date of birth, gender, and user type). #77 
- [TASK] Implement validation for required fields (name, email, password) and user type selection. #61 
- [TASK] Implement backend API for account registration that saves user details and user type. #62
- [TASK] Provide feedback messages for successful registration or validation errors. #63

### Implementation Breakdown:
- Design the registration form with fields for name, email, password, date of birth, gender, and a dropdown to select user type (Host or Tenant).
- Add input validation for email format, password strength, and required fields.
- Create an API endpoint to handle the registration process, saving user details to the database and sending a confirmation email upon successful registration.
- Integrate the registration form with the backend API to ensure correct data submission and user feedback.

### Testing:

- **Unit Tests:**
  - **Frontend Unit Tests:** Ensure the registration form displays correctly and validates input (e.g., email format, required fields).
  - **Backend Unit Tests:** Test the registration API for proper handling of input validation, user creation, and confirmation email dispatch.
  
- **Integration Tests:**
  - **Frontend Integration Tests:** Verify the registration form submission with the backend API and check for correct feedback messages.
  - **Backend Integration Tests:** Confirm the API processes registration requests and updates the database accurately.
  
- **End-to-End Testing:**
  - Simulate the complete user flow for account registration, ensuring functionality from form submission to email confirmation.

**Comment by CarlaShawi** [comment]
reopened as it is still missing unit and end to end testing

**Comment by CarlaShawi** [comment]
The user story will be moved to Sprint 3 as both unit tests and end-to-end testing for this user story haven't been completed yet.
