### ISSUE TITLE
[US] Admin Viewing Dashboard 

### ISSUE THREAD

**Issue by Tharsipa** [harismah/Dwella#358]
### Description:
As an admin, I want to log in and access the admin-specific dashboard so that I can manage and oversee platform activities effectively.

### Story Points:
5

### Priority:
1

### Risk:
Medium

### Business Value:
H (High)

### Child of (if applicable):
Epic 12: Moderator Features [#357]

### Acceptance Criteria:

- Admin users should be able to log in with valid admin credentials.
- Upon successful login, the admin should be redirected to an admin-specific dashboard.
- The dashboard should display key administrative functionalities (e.g., user management, listings overview, analytics).
- Non-admin users should not have access to admin pages.

### Task Breakdown (if applicable):

- #359 
- #361 

### Implementation Breakdown:

- Create a separate route for the admin dashboard.
- Ensure the login system checks for admin roles and redirects appropriately.
- Implement components to display admin-specific features and statistics.
- Add access control middleware to restrict access to admin routes.

### Testing:

- **Unit Tests**: Test login functionality for admin users and role-based redirects.
- **Integration Tests**: Verify access to admin pages is restricted to admin users only.
- **End-to-End Tests**: Ensure admin users can log in and access all key dashboard features successfully.

**Comment by CarlaShawi** [comment]
closed by pr #373
