### ISSUE TITLE
[TASK] Backend: Implement Admin Login and Access Control

### ISSUE THREAD

**Issue by Tharsipa** [harismah/Dwella#361]
**Description:**  
Develop the backend functionality for admin authentication and access control. This will allow administrators to securely log in and access protected administrative routes and functionalities. The implementation should include robust authentication mechanisms, role-based access controls, and session management to ensure that only authorized users can perform administrative tasks.

Related to **user story** [#358 ]

**Comment by CarlaShawi** [comment]
resolved in pr #373
