### ISSUE TITLE
[US] Management of Listing: Being able to remove listings, view listings 

### ISSUE THREAD

**Issue by raccoonrick** [harismah/Dwella#368]
### Description:

As an admin/moderator, I want to be able to view and remove all listings so that I can effectively manage all the listings and make sure the displayed listings are relevant and accurate.

### Story Points:

5

### Priority:

2

### Risk:

Medium

### Business Value:

H (High)

### Child of (if applicable) :

Epic 12: Moderator Features [#357]

### Acceptance Criteria:

- Admin users should be able to view all listings available on the application
- Admin users should be able to remove listings and delete them from the database
- Users that are not moderators or admins should not be able to access this feature

### Task Breakdown (if applicable):

- #375
- #374

### Implementation Breakdown:
- Create API routes for getting listings and for removing certain listings
- Ensure that these routes are only accessible to admin users
- Implement frontend page for Manage Listings

### Testing (if applicable):

- **Unit Tests**: Test fetching all listings and removing listings from the database
- **Integration Tests**: Verify that only admin users can access the page and be able to view/remove listings for the website

**Comment by louisa-lina** [comment]
US resolved with PR #377
