### ISSUE TITLE
[US] Email Verification

### ISSUE THREAD

**Issue by v-vasco** [harismah/Dwella#38]
### Description:
As a user, I want to be able to change my email address so that I can receive messages from the app to my new preferred address. As a user, I want to be able to verify my email address so that I can make sure I provided the right email address that I can access.

### Story Points:
2

### Priority:
3 (Low)

### Risk:
Low

### Business Value:
L (Low)

### Child of (if applicable) :
 - #36 

### Acceptance Criteria:
•⁠  ⁠The feature should send an email to the email address provided with a unique verification link upon creating an account.
•⁠  ⁠The feature should send an email to the email address provided with a unique link upon a user changing their email address.
•⁠  ⁠The feature should provide error handling in case of invalid emails.
•⁠  ⁠Clicking the verification link successfully verifies the user's email address.
•⁠  ⁠Verified users can log in to the application.
•⁠  ⁠Users can request a new verification email if the previous one expires or if they didn’t receive it.
•⁠  ⁠A success message is shown when users verify their email.
•⁠  ⁠An error message is displayed for expired or invalid tokens.

### Task Breakdown:
- #52 
- #51 
- #86 

### Implementation Breakdown:
UI/UX Design: Create user-friendly email verification pages, including success, error, and resend email windows. Ensure the design aligns with the overall platform UI/UX.

Email Sending Logic: Integrate with an email service provider (e.g., SendGrid or Nodemailer) to send verification emails upon user signup, containing a link with a unique token.

Token Verification API: Develop an API endpoint that verifies the token and updates the user's account to mark the email as verified. Handle cases where the token is expired or invalid.

Resend Verification Email: Implement a frontend interface allowing users to request another verification email if they didn't receive the first one or it has expired.

Frontend-Backend Integration: Ensure the frontend displays appropriate feedback (e.g., success or error messages) based on the server's response after the user clicks the verification link. Redirect verified users to the login page.

Session Logic: Users attempting to log in without a verified email should be prevented from accessing the dashboard and prompted to verify their email.

### Testing:
•Unit Tests:

 - Frontend Unit Tests: Test UI components like success and error messages, and the resend email button functionality.
Backend Unit Tests: Test the verification token generation, email sending, and token verification logic, ensuring proper error handling (e.g., expired or invalid tokens).
Integration Tests:

- Frontend Integration Tests: Test the end-to-end flow of users receiving verification emails, clicking the link, and getting feedback based on the token status.

•Backend Integration Tests: Test the connection between the signup process, token generation, and email verification API to ensure users' emails are correctly marked as verified.

•End-to-End Testing: Simulate the complete user flow from signup to email verification, including sending the email, clicking the verification link, and logging in after verification.

**Comment by CarlaShawi** [comment]
The user story will be moved to Sprint 3 as both unit tests and end-to-end testing for this user story haven't been completed yet.

**Comment by CarlaShawi** [comment]
This user story will be closed as all tasks have been completed successfully.
