### ISSUE TITLE
[US] Search Bar 

### ISSUE THREAD

**Issue by v-vasco** [harismah/Dwella#39]
### Description:
As a lessee, I want to be able to search keywords when looking at listings so that I can see only listings that mention those keywords since they might not be covered by the listing filters.

### Story Points:
8

### Priority:
2 (medium)

### Risk:
Medium

### Business Value:
H (high)

### Child of (if applicable) :
 - #44 

### Acceptance Criteria:
- The feature should show users all listings containing their search term(s).
- The feature should rank the search results based on how closely the listing match the search term(s).
- The feature should apply the keyword search on the listings that meet the user's filters.
- The feature should provide error handling should the search not return any listings.

### Task Breakdown (if applicable):
- #150 

### Implementation Breakdown:
- [Outline the major implementation steps.]

### Testing (if applicable):
- **Unit Tests**: [Describe any unit tests needed]
- **Integration Tests**: [Describe any integration tests needed]

**Comment by NicholasWahome** [comment]
This is now closed as it has been implemented in #150
