### ISSUE TITLE
[US] View all available listings

### ISSUE THREAD

**Issue by NicholasWahome** [harismah/Dwella#42]
### Description:
As a user, I want to view all available listings so that I can browse through the options and make an informed selection.

### Story Points:
3

### Priority:
2

### Risk:
Low

### Business Value:
Medium

### Child of (if applicable) :
- #44 

### Acceptance Criteria:
- The user should be able to view a paginated list of all available listings.
- The listings should display essential details such as name, location, price, and availability.
- The user should be able to filter or sort the listings by price, location, or other attributes.
- The user interface should load listings efficiently and handle a large number of results.

### Task Breakdown (if applicable):
- [x] #124
- [x] #127
- [x] #129

### Implementation Breakdown:
- Design the API endpoint to query available listings, supporting pagination, filtering, and sorting.
- Implement the frontend component to display listings in a responsive and user-friendly manner.
- Add the functionality for sorting by attributes like price and location.
- Implement efficient pagination to ensure that the user can browse large datasets smoothly.
- Ensure proper error handling for cases where no listings are available.

### Testing (if applicable):
- Unit Tests: Test the backend API to ensure correct data retrieval for listings.
- Integration Tests: Verify that the frontend and backend communicate properly, ensuring that listings are displayed, filtered, and paginated correctly.

**Comment by louisa-lina** [comment]
Hi, I linked your issue to  Display Listing Details.

**Comment by NicholasWahome** [comment]
I think you linked the wrong issue. As it is not the epic. Making the switch to #44

**Comment by louisa-lina** [comment]
Perfect
