### ISSUE TITLE
[US] Account Signing in And Logging Out

### ISSUE THREAD

**Issue by CarlaShawi** [harismah/Dwella#46]
### Description:
As a user, I want to log in and sign out of my account to securely access and manage my profile, and listings, and match with potential roommates.

### Story Points:
3

### Priority:
1

### Risk:
Medium

### Business Value:
H (High)

### Child of:
Epic Account Management & Verification #36 

### Acceptance Criteria:
- Users can log in with their registered email and password.
- Upon successful login, users are redirected to their dashboard.
- Users can securely log out from any page in the application.
- Invalid login attempts (e.g., wrong password) display an error message.
- Authentication should be handled securely.
- Logout clears user session data and redirects to the homepage.

### Task Breakdown:
- #65

### Implementation Breakdown:
- **UI/UX Design**: Create a login form with email and password fields.  And Implement easy and intuitive design for users to easily sign in and out at any time.
- **Validation**: Implement validation to ensure email and password fields are not empty and display appropriate error messages for invalid inputs.
- **Backend API**: Develop authentication API endpoints for login, which verifies user credentials, and an endpoint for logging out to invalidate the session.
- **Frontend-Backend Integration**: Connect the login form and logout button to the backend API, allowing users to log in and out securely.
- **Feedback**: Provide feedback to users when login attempts succeed or fail, and ensure a smooth user experience when logging out.

### Testing:
- **Unit Tests**: 
  - Frontend Unit Tests: Test the functionality of the login form, including input validation (e.g., required fields, invalid email format).
  - Backend Unit Tests: Test the API endpoint for user login to ensure proper handling of credentials, and session creation.
  
- **Integration Tests**: 
  - Frontend Integration Tests: Test the integration between the login form and the authentication API, ensuring successful login redirects the user to the dashboard, and errors are displayed for invalid credentials.
  - Backend Integration Tests: Validate the session management logic (e.g., token handling) to ensure users can log in and out correctly across multiple devices.

- **End-to-End Testing**:
  - Simulate the complete user flow from logging into and logging out, ensuring functionality.

**Comment by raccoonrick** [comment]
Closes with #78
