### ISSUE TITLE
[Documentation] Add labels

### ISSUE THREAD

**Issue by harismah** [harismah/Dwella#5]
**Description:** To improve organization and streamline tracking of issues related to specific features in the Dwella project, we need to create additional GitHub labels that represent core features of the project. This will help the team quickly identify and categorize issues based on the feature they relate to, enhancing our workflow efficiency and communication.

Information found on: https://github.com/CodePioneerX/Dwella/labels

**Comment by harismah** [comment]
Based on the curated breakdown of Epic, user stories created alongside with @CarsonSSk. Labels with common topics have been grouped under a singular related feature and have been created. 
[Requirements & User Stories.pdf](https://github.com/user-attachments/files/17091501/Requirements.User.Stories.pdf)

**Comment by CarsonSSk** [comment]
Hey @CodePioneerX , I took a look at the labels you created and after cross-referencing them with our features, all looks good. Thanks!
