### ISSUE TITLE
[Documentation] Deployment Diagram

### ISSUE THREAD

**Issue by Swaggyyyy2** [harismah/Dwella#9]
**Description:** 

This issue involves creating a detailed deployment plan and infrastructure documentation for the Dwella project. The goal is to outline the deployment strategy, infrastructure setup, and release process for each stage (Stakeholder Signoff, Family and Friends Testing, Alpha Release, Beta Release, and Full Release) using Docker and CI/CD workflows. This will ensure a smooth, efficient, and well-organized deployment pipeline with robust environment management and automated testing.

Information can be found on (Wiki): https://github.com/CodePioneerX/Dwella/wiki/Deployment-Plan-and-Infrastructure

**Comment by Swaggyyyy2** [comment]
Initial conceptualization of the deployment diagram created with @CodePioneerX .
![deployment diagaram](https://github.com/user-attachments/assets/066827f7-9a2f-49af-a4fc-54ea8bad972c)

**Comment by harismah** [comment]
Revision of Deployment Diagram: includes interconnections, testing, docker containerization, and future cloud-based hosting infrastructure. 

![Deployment Diagram](https://github.com/user-attachments/assets/ec2610a3-932f-42a6-9112-1bff4bef92e0)

**Comment by harismah** [comment]
Professor Signed off on the diagram during office hours held on 26/09/2024

**Comment by CarsonSSk** [comment]
Thanks, closing issue now!
