### ISSUE TITLE
[TEST] Cypress End-to-End Testing and Unit Testing for Login/Sign Out

### ISSUE THREAD

**Issue by CarlaShawi** [harismah/Dwella#91]
**Description**: The goal of this task is to ensure the login and sign-out functionality works correctly through comprehensive end-to-end testing using Cypress. Key scenarios include successful login with valid credentials, handling of incorrect login attempts, and proper sign-out functionality that securely clears user sessions.

Related to user story: #46
PR resolving this issue: #142

**Comment by raccoonrick** [comment]
Closed with [#142]
