### ISSUE TITLE
[TEST] Cypress End-to-End Testing and Unit Testing for Viewing and Editing Personal Profile

### ISSUE THREAD

**Issue by CarlaShawi** [harismah/Dwella#92]
**Description**: The goal of this task is to ensure the functionality for viewing and editing personal profiles works correctly through comprehensive end-to-end testing using Cypress. Key scenarios include viewing the profile with correct user data, editing fields like their personal information, uploading personal profile image and saving updates to the database.

Related to issues: [#25, #28, #32]
PR closing this issue: #142

**Comment by raccoonrick** [comment]
Closed with [#142]
