### ISSUE TITLE
[TEST] Cypress End-to-End Testing Governmental Verification ID

### ISSUE THREAD

**Issue by CarlaShawi** [harismah/Dwella#94]
**Description**: The goal of this task is to ensure the proper functionality of the Governmental Verification ID feature, allowing users to upload their government-issued identification for verification. Cypress will be used for end-to-end testing to simulate user interactions, such as uploading valid ID types (driver's license, etc..), file validation, and receiving verification feedback

Related to: [#26]
PR resolving: #329

**Comment by NicholasWahome** [comment]
Completed this issue
